[package]
name = "assignment_2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
num = "0.4.3"
rayon = "1.10.0"
num_cpus = "1.16.0"
csv = "1.3.1"

[profile.release]
overflow-checks = true

[profile.dev]
opt-level = 3